# Generated by Django 4.2.11 on 2024-04-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0005_instance_versioninstance_versioninstance_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="availability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lost", "lost"),
                    ("available", "available"),
                    ("non-accessible", "non-accessible"),
                ],
                max_length=15,
                null=True,
                verbose_name="Availability",
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="item_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Item description"
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="tibschol_ref",
            field=models.TextField(
                blank=True, null=True, verbose_name="Tibschol reference"
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="zotero_ref",
            field=models.TextField(blank=True, null=True, verbose_name="Zotero"),
        ),
        migrations.AddField(
            model_name="versioninstance",
            name="availability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lost", "lost"),
                    ("available", "available"),
                    ("non-accessible", "non-accessible"),
                ],
                max_length=15,
                null=True,
                verbose_name="Availability",
            ),
        ),
        migrations.AddField(
            model_name="versioninstance",
            name="item_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Item description"
            ),
        ),
        migrations.AddField(
            model_name="versioninstance",
            name="tibschol_ref",
            field=models.TextField(
                blank=True, null=True, verbose_name="Tibschol reference"
            ),
        ),
        migrations.AddField(
            model_name="versioninstance",
            name="zotero_ref",
            field=models.TextField(blank=True, null=True, verbose_name="Zotero"),
        ),
    ]
