# Generated by Django 4.2.11 on 2024-04-22 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "apis_ontology",
            "0006_instance_availability_instance_item_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instance",
            options={"verbose_name": "instance", "verbose_name_plural": "Instances"},
        ),
    ]
