# Generated by Django 4.2.13 on 2024-05-19 00:22

import apis_core.generic.abc
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0008_instancecopiedwrittendownatplace_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Excerpts",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xml_id", models.CharField(max_length=255, unique=True)),
                ("xml_content", models.TextField()),
                ("source", models.CharField(max_length=255, unique=True)),
            ],
            bases=(models.Model,),
        ),
    ]
