# Generated by Django 4.2.13 on 2024-05-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0009_excerpts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="excerpts",
            name="source",
            field=models.CharField(max_length=255),
        ),
    ]
