# Generated by Django 4.2.13 on 2024-06-02 21:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0010_alter_excerpts_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="place",
            name="end_end_date",
        ),
        migrations.RemoveField(
            model_name="place",
            name="end_start_date",
        ),
        migrations.RemoveField(
            model_name="versionplace",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="versionplace",
            name="end_end_date",
        ),
        migrations.RemoveField(
            model_name="versionplace",
            name="end_start_date",
        ),
    ]
