# Generated by Django 4.2.13 on 2024-06-02 21:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0011_remove_place_end_date_remove_place_end_end_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instance",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="instance",
            name="end_end_date",
        ),
        migrations.RemoveField(
            model_name="instance",
            name="end_start_date",
        ),
        migrations.RemoveField(
            model_name="versioninstance",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="versioninstance",
            name="end_end_date",
        ),
        migrations.RemoveField(
            model_name="versioninstance",
            name="end_start_date",
        ),
        migrations.RemoveField(
            model_name="versionwork",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="versionwork",
            name="end_end_date",
        ),
        migrations.RemoveField(
            model_name="versionwork",
            name="end_start_date",
        ),
        migrations.RemoveField(
            model_name="work",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="work",
            name="end_end_date",
        ),
        migrations.RemoveField(
            model_name="work",
            name="end_start_date",
        ),
    ]
