# Generated by Django 4.2.13 on 2024-06-02 22:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0013_remove_instance_published_remove_person_published_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instance",
            name="end_date_written",
        ),
        migrations.RemoveField(
            model_name="place",
            name="end_date_written",
        ),
        migrations.RemoveField(
            model_name="versioninstance",
            name="end_date_written",
        ),
        migrations.RemoveField(
            model_name="versionplace",
            name="end_date_written",
        ),
        migrations.RemoveField(
            model_name="versionwork",
            name="end_date_written",
        ),
        migrations.RemoveField(
            model_name="work",
            name="end_date_written",
        ),
    ]
