# Generated by Django 4.2.13 on 2024-06-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0014_remove_instance_end_date_written_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="place",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="versioninstance",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="versionplace",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="versionwork",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="work",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
