# Generated by Django 4.2.13 on 2024-06-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0014_remove_instance_end_date_written_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="start_date_written",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="end_date_written",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Life date end"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="start_date_written",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Life date start"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="start_date_written",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="versioninstance",
            name="start_date_written",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="end_date_written",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Life date end"
            ),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="start_date_written",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Life date start"
            ),
        ),
        migrations.AlterField(
            model_name="versionplace",
            name="start_date_written",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="isExtant",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Is extant"
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="start_date_written",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Date of composition",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="isExtant",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Is extant"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="start_date_written",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Date of composition",
            ),
        ),
    ]
