# Generated by Django 4.2.13 on 2024-06-13 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0015_alter_instance_start_date_written_and_more"),
        (
            "apis_ontology",
            "0016_remove_instance_published_remove_person_published_and_more",
        ),
    ]

    operations = []
