# Generated by Django 4.2.13 on 2024-06-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0017_merge_20240613_1354"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="label",
            field=models.CharField(blank=True, default="", verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="versionplace",
            name="label",
            field=models.CharField(blank=True, default="", verbose_name="Name"),
        ),
    ]
