# Generated by Django 4.2.13 on 2024-07-10 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0018_alter_place_label_alter_versionplace_label"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="versionperson_collection",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="versionperson_collection",
            name="history",
        ),
        migrations.RemoveField(
            model_name="versionperson_collection",
            name="person",
        ),
        migrations.RemoveField(
            model_name="versionplace_collection",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="versionplace_collection",
            name="history",
        ),
        migrations.RemoveField(
            model_name="versionplace_collection",
            name="place",
        ),
        migrations.RemoveField(
            model_name="versionwork_collection",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="versionwork_collection",
            name="history",
        ),
        migrations.RemoveField(
            model_name="versionwork_collection",
            name="work",
        ),
        migrations.RemoveField(
            model_name="instance",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="person",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="place",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="work",
            name="collection",
        ),
        migrations.DeleteModel(
            name="VersionInstance_collection",
        ),
        migrations.DeleteModel(
            name="VersionPerson_collection",
        ),
        migrations.DeleteModel(
            name="VersionPlace_collection",
        ),
        migrations.DeleteModel(
            name="VersionWork_collection",
        ),
    ]
