# Generated by Django 4.2.13 on 2024-07-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0021_persondirectpredecessorinlineageofperson_subject_of_teaching_vocab_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="personstudentofperson",
            name="subject_of_teaching_vocab",
            field=models.ManyToManyField(
                blank=True,
                to="apis_ontology.subject",
                verbose_name="Subject of teaching",
            ),
        ),
        migrations.AlterField(
            model_name="persondirectpredecessorinlineageofperson",
            name="subject_of_teaching",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="subject of teaching",
            ),
        ),
        migrations.AlterField(
            model_name="persondiscipleofperson",
            name="subject_of_teaching",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="subject of teaching",
            ),
        ),
        migrations.AlterField(
            model_name="personreferswithnametotheviewsofperson",
            name="subject_of_teaching",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="subject of teaching",
            ),
        ),
        migrations.AlterField(
            model_name="personreferswithoutnametotheviewsofperson",
            name="subject_of_teaching",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="subject of teaching",
            ),
        ),
        migrations.AlterField(
            model_name="personstudentofperson",
            name="subject_of_teaching",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="subject of teaching",
            ),
        ),
    ]
