# Generated by Django 4.2.13 on 2024-07-03 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0022_personstudentofperson_subject_of_teaching_vocab_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="persondirectpredecessorinlineageofperson",
            name="subject_of_teaching",
        ),
        migrations.RemoveField(
            model_name="persondiscipleofperson",
            name="subject_of_teaching",
        ),
        migrations.RemoveField(
            model_name="personreferswithnametotheviewsofperson",
            name="subject_of_teaching",
        ),
        migrations.RemoveField(
            model_name="personreferswithoutnametotheviewsofperson",
            name="subject_of_teaching",
        ),
        migrations.RemoveField(
            model_name="personrequestorofperson",
            name="subject_of_teaching",
        ),
        migrations.RemoveField(
            model_name="personstudentofperson",
            name="subject_of_teaching",
        ),
        migrations.RemoveField(
            model_name="versionwork",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="work",
            name="subject",
        ),
    ]
