# Generated by Django 4.2.13 on 2024-07-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0023_remove_persondirectpredecessorinlineageofperson_subject_of_teaching_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="personactiveatplace",
            name="subject_of_teaching_vocab",
            field=models.ManyToManyField(
                blank=True,
                to="apis_ontology.subject",
                verbose_name="Subject of teaching",
            ),
        ),
    ]
