# Generated by Django 4.2.14 on 2024-07-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0024_personactiveatplace_subject_of_teaching_vocab"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instanceiscopiedfrominstance",
            options={"verbose_name": "instance has as its source"},
        ),
        migrations.AlterField(
            model_name="instance",
            name="provenance",
            field=models.TextField(blank=True, null=True, verbose_name="Provenance"),
        ),
        migrations.AlterField(
            model_name="versioninstance",
            name="provenance",
            field=models.TextField(blank=True, null=True, verbose_name="Provenance"),
        ),
    ]
