# Generated by Django 4.2.16 on 2024-10-11 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0028_remove_versionperson_collection_collection_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="versioninstance",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "Version",
                "verbose_name_plural": "Versions",
            },
        ),
        migrations.AlterModelOptions(
            name="versionperson",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "Version",
                "verbose_name_plural": "Versions",
            },
        ),
        migrations.AlterModelOptions(
            name="versionplace",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "Version",
                "verbose_name_plural": "Versions",
            },
        ),
        migrations.AlterModelOptions(
            name="versionwork",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "Version",
                "verbose_name_plural": "Versions",
            },
        ),
    ]
