# Generated by Django 4.2.16 on 2024-10-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0019_remove_versionperson_collection_collection_and_more"),
        ("apis_ontology", "0029_alter_versioninstance_options_and_more"),
    ]

    operations = []
