# Generated by Django 5.1.2 on 2024-11-05 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0029_alter_versioninstance_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="versioninstance",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical instance",
                "verbose_name_plural": "historical Instances",
            },
        ),
        migrations.AlterModelOptions(
            name="versionperson",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical person",
                "verbose_name_plural": "historical Persons",
            },
        ),
        migrations.AlterModelOptions(
            name="versionplace",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical place",
                "verbose_name_plural": "historical Places",
            },
        ),
        migrations.AlterModelOptions(
            name="versionwork",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical work",
                "verbose_name_plural": "historical Works",
            },
        ),
    ]
