# Generated by Django 5.1.3 on 2024-11-17 00:11

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0031_versioninstancecopiedwrittendownatplace_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="name",
            new_name="name_latin",
        ),
        migrations.RenameField(
            model_name="versionperson",
            old_name="name",
            new_name="name_latin",
        ),
        migrations.CreateModel(
            name="PersonTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Name"
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="apis_ontology.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "person Translation",
                "db_table": "apis_ontology_person_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.RunSQL(
            "INSERT INTO apis_ontology_person_translation(language_code, name , master_id) SELECT 'en', name_latin, rootobject_ptr_id FROM apis_ontology_person;"
        ),
    ]
