# Generated by Django 5.1.3 on 2024-12-04 11:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0031_versioninstancecopiedwrittendownatplace_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="versionpersoneditorofinstance",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="versionpersoneditorofinstance",
            name="obj_content_type",
        ),
        migrations.RemoveField(
            model_name="versionpersoneditorofinstance",
            name="relation_ptr",
        ),
        migrations.RemoveField(
            model_name="versionpersoneditorofinstance",
            name="subj_content_type",
        ),
        migrations.DeleteModel(
            name="PersonEditorOfInstance",
        ),
        migrations.DeleteModel(
            name="VersionPersonEditorOfInstance",
        ),
    ]
