# Generated by Django 5.1.3 on 2024-12-04 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0032_remove_versionpersoneditorofinstance_history_user_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="versionpersonillustratorofinstance",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="versionpersonillustratorofinstance",
            name="obj_content_type",
        ),
        migrations.RemoveField(
            model_name="versionpersonillustratorofinstance",
            name="relation_ptr",
        ),
        migrations.RemoveField(
            model_name="versionpersonillustratorofinstance",
            name="subj_content_type",
        ),
        migrations.DeleteModel(
            name="PersonIllustratorOfInstance",
        ),
        migrations.DeleteModel(
            name="VersionPersonIllustratorOfInstance",
        ),
    ]
