# Generated by Django 5.1.3 on 2024-12-04 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0033_remove_versionpersonillustratorofinstance_history_user_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="versionpersonlenderofinstance",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="versionpersonlenderofinstance",
            name="obj_content_type",
        ),
        migrations.RemoveField(
            model_name="versionpersonlenderofinstance",
            name="relation_ptr",
        ),
        migrations.RemoveField(
            model_name="versionpersonlenderofinstance",
            name="subj_content_type",
        ),
        migrations.DeleteModel(
            name="PersonLenderOfInstance",
        ),
        migrations.DeleteModel(
            name="VersionPersonLenderOfInstance",
        ),
    ]
