# Generated by Django 5.1.3 on 2024-12-04 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0034_remove_versionpersonlenderofinstance_history_user_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="versionpersonspiritualfriendofperson",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="versionpersonspiritualfriendofperson",
            name="obj_content_type",
        ),
        migrations.RemoveField(
            model_name="versionpersonspiritualfriendofperson",
            name="relation_ptr",
        ),
        migrations.RemoveField(
            model_name="versionpersonspiritualfriendofperson",
            name="subj_content_type",
        ),
        migrations.DeleteModel(
            name="PersonSpiritualFriendOfPerson",
        ),
        migrations.DeleteModel(
            name="VersionPersonSpiritualFriendOfPerson",
        ),
    ]
