# Generated by Django 5.1.3 on 2024-12-04 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0035_remove_versionpersonspiritualfriendofperson_history_user_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="versionpersonpromoterofwork",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="versionpersonpromoterofwork",
            name="obj_content_type",
        ),
        migrations.RemoveField(
            model_name="versionpersonpromoterofwork",
            name="relation_ptr",
        ),
        migrations.RemoveField(
            model_name="versionpersonpromoterofwork",
            name="subj_content_type",
        ),
        migrations.DeleteModel(
            name="PersonPromoterOfWork",
        ),
        migrations.DeleteModel(
            name="VersionPersonPromoterOfWork",
        ),
    ]
