# Generated by Django 5.1.3 on 2024-12-04 11:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0036_remove_versionpersonpromoterofwork_history_user_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="versionpersonpatronofperson",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="versionpersonpatronofperson",
            name="obj_content_type",
        ),
        migrations.RemoveField(
            model_name="versionpersonpatronofperson",
            name="relation_ptr",
        ),
        migrations.RemoveField(
            model_name="versionpersonpatronofperson",
            name="subj_content_type",
        ),
        migrations.DeleteModel(
            name="PersonPatronOfPerson",
        ),
        migrations.DeleteModel(
            name="VersionPersonPatronOfPerson",
        ),
    ]
