# Generated by Django 5.1.3 on 2024-12-04 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0037_remove_versionpersonpatronofperson_history_user_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="versionpersonfellowstudentofperson",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="versionpersonfellowstudentofperson",
            name="obj_content_type",
        ),
        migrations.RemoveField(
            model_name="versionpersonfellowstudentofperson",
            name="relation_ptr",
        ),
        migrations.RemoveField(
            model_name="versionpersonfellowstudentofperson",
            name="subj_content_type",
        ),
        migrations.DeleteModel(
            name="PersonFellowStudentOfPerson",
        ),
        migrations.DeleteModel(
            name="VersionPersonFellowStudentOfPerson",
        ),
    ]
