# Generated by Django 5.1.3 on 2024-12-04 11:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0038_remove_versionpersonfellowstudentofperson_history_user_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="versionpersonauntmaternalpaternalofperson",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="versionpersonauntmaternalpaternalofperson",
            name="obj_content_type",
        ),
        migrations.RemoveField(
            model_name="versionpersonauntmaternalpaternalofperson",
            name="relation_ptr",
        ),
        migrations.RemoveField(
            model_name="versionpersonauntmaternalpaternalofperson",
            name="subj_content_type",
        ),
        migrations.DeleteModel(
            name="PersonAuntMaternalPaternalOfPerson",
        ),
        migrations.DeleteModel(
            name="VersionPersonAuntMaternalPaternalOfPerson",
        ),
    ]
