# Generated by Django 5.1.3 on 2024-12-04 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0039_remove_versionpersonauntmaternalpaternalofperson_history_user_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="versionpersonfellowmonkofperson",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="versionpersonfellowmonkofperson",
            name="obj_content_type",
        ),
        migrations.RemoveField(
            model_name="versionpersonfellowmonkofperson",
            name="relation_ptr",
        ),
        migrations.RemoveField(
            model_name="versionpersonfellowmonkofperson",
            name="subj_content_type",
        ),
        migrations.DeleteModel(
            name="PersonFellowMonkOfPerson",
        ),
        migrations.DeleteModel(
            name="VersionPersonFellowMonkOfPerson",
        ),
    ]
