# Generated by Django 5.1.3 on 2024-12-04 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0041_personhasotherrelationwithinstance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workquoteswithnametheviewsofperson",
            name="relation_ptr",
        ),
        migrations.DeleteModel(
            name="VersionWorkQuotesWithNameTheViewsOfPerson",
        ),
        migrations.DeleteModel(
            name="WorkQuotesWithNameTheViewsOfPerson",
        ),
    ]
