# Generated by Django 5.1.3 on 2024-12-04 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0042_remove_workquoteswithnametheviewsofperson_relation_ptr_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workquoteswithoutnametheviewsofperson",
            name="relation_ptr",
        ),
        migrations.DeleteModel(
            name="VersionWorkQuotesWithoutNameTheViewsOfPerson",
        ),
        migrations.DeleteModel(
            name="WorkQuotesWithoutNameTheViewsOfPerson",
        ),
    ]
