# Generated by Django 5.1.3 on 2024-12-10 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "apis_ontology",
            "0043_remove_workquoteswithoutnametheviewsofperson_relation_ptr_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="versionpersondiscipleofperson_subject_of_teaching_vocab",
            name="persondiscipleofperson",
        ),
        migrations.RemoveField(
            model_name="versionpersondiscipleofperson",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="versionpersondiscipleofperson",
            name="obj_content_type",
        ),
        migrations.RemoveField(
            model_name="versionpersondiscipleofperson",
            name="relation_ptr",
        ),
        migrations.RemoveField(
            model_name="versionpersondiscipleofperson",
            name="subj_content_type",
        ),
        migrations.RemoveField(
            model_name="versionpersondiscipleofperson_subject_of_teaching_vocab",
            name="history",
        ),
        migrations.RemoveField(
            model_name="versionpersondiscipleofperson_subject_of_teaching_vocab",
            name="subject",
        ),
        migrations.DeleteModel(
            name="PersonDiscipleOfPerson",
        ),
        migrations.DeleteModel(
            name="VersionPersonDiscipleOfPerson",
        ),
        migrations.DeleteModel(
            name="VersionPersonDiscipleOfPerson_subject_of_teaching_vocab",
        ),
    ]
