# Generated by Django 5.1.3 on 2024-12-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "apis_ontology",
            "0044_remove_versionpersondiscipleofperson_subject_of_teaching_vocab_persondiscipleofperson_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="versionpersonannotatorofinstance",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="versionpersonannotatorofinstance",
            name="obj_content_type",
        ),
        migrations.RemoveField(
            model_name="versionpersonannotatorofinstance",
            name="relation_ptr",
        ),
        migrations.RemoveField(
            model_name="versionpersonannotatorofinstance",
            name="subj_content_type",
        ),
        migrations.DeleteModel(
            name="PersonAnnotatorOfInstance",
        ),
        migrations.DeleteModel(
            name="VersionPersonAnnotatorOfInstance",
        ),
    ]
