# Generated by Django 5.1.3 on 2024-12-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "apis_ontology",
            "0045_remove_versionpersonannotatorofinstance_history_user_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worknamesperson",
            name="relation_ptr",
        ),
        migrations.DeleteModel(
            name="VersionWorkNamesPerson",
        ),
        migrations.DeleteModel(
            name="WorkNamesPerson",
        ),
    ]
