# Generated by Django 5.1.3 on 2024-12-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0046_remove_worknamesperson_relation_ptr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worknameswork",
            name="relation_ptr",
        ),
        migrations.DeleteModel(
            name="VersionWorkNamesWork",
        ),
        migrations.DeleteModel(
            name="WorkNamesWork",
        ),
    ]
