# Generated by Django 5.1.3 on 2024-12-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0047_remove_worknameswork_relation_ptr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="versionpersonciteswork",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="versionpersonciteswork",
            name="obj_content_type",
        ),
        migrations.RemoveField(
            model_name="versionpersonciteswork",
            name="relation_ptr",
        ),
        migrations.RemoveField(
            model_name="versionpersonciteswork",
            name="subj_content_type",
        ),
        migrations.DeleteModel(
            name="PersonCitesWork",
        ),
        migrations.DeleteModel(
            name="VersionPersonCitesWork",
        ),
    ]
