# Generated by Django 5.1.3 on 2024-12-11 10:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0048_remove_versionpersonciteswork_history_user_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("relations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InstanceCopiedWrittenDownAtPlace",
            new_name="InstanceWrittenAtPlace",
        ),
        migrations.RenameModel(
            old_name="VersionInstanceCopiedWrittenDownAtPlace",
            new_name="VersionInstanceWrittenAtPlace",
        ),
        migrations.AlterModelOptions(
            name="versioninstancewrittenatplace",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical instance written at place",
                "verbose_name_plural": "historical instance written at places",
            },
        ),
    ]
