# Generated by Django 5.1.3 on 2024-12-11 10:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "apis_ontology",
            "0049_rename_instancecopiedwrittendownatplace_instancewrittenatplace_and_more",
        ),
        ("contenttypes", "0002_remove_content_type_name"),
        ("relations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PersonDirectPredecessorInLineageOfPerson",
            new_name="PersonLineagePredecessorOfPerson",
        ),
        migrations.RenameModel(
            old_name="VersionPersonDirectPredecessorInLineageOfPerson",
            new_name="VersionPersonLineagePredecessorOfPerson",
        ),
        migrations.RenameModel(
            old_name="VersionPersonDirectPredecessorInLineageOfPerson_subject_of_teaching_vocab",
            new_name="VersionPersonLineagePredecessorOfPerson_subject_of_teaching_vocab",
        ),
        migrations.AlterModelOptions(
            name="instanceiscopiedfrominstance",
            options={"verbose_name": "instance has source"},
        ),
        migrations.AlterModelOptions(
            name="versioninstanceiscopiedfrominstance",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical instance has source",
                "verbose_name_plural": "historical instance has sources",
            },
        ),
        migrations.AlterModelOptions(
            name="versionpersonlineagepredecessorofperson",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical person lineage predecessor of person",
                "verbose_name_plural": "historical person lineage predecessor of persons",
            },
        ),
        migrations.AlterModelOptions(
            name="versionpersonlineagepredecessorofperson_subject_of_teaching_vocab",
            options={
                "verbose_name": "VersionPersonLineagePredecessorOfPerson_subject_of_teaching_vocab"
            },
        ),
        migrations.RenameField(
            model_name="versionpersonlineagepredecessorofperson_subject_of_teaching_vocab",
            old_name="persondirectpredecessorinlineageofperson",
            new_name="personlineagepredecessorofperson",
        ),
    ]
