# Generated by Django 5.1.3 on 2024-12-11 10:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "apis_ontology",
            "0050_rename_persondirectpredecessorinlineageofperson_personlineagepredecessorofperson_and_more",
        ),
        ("contenttypes", "0002_remove_content_type_name"),
        ("relations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PersonHasOtherTypeOfPersonalRelationToPerson",
            new_name="PersonOtherRelationToPerson",
        ),
        migrations.RenameModel(
            old_name="VersionPersonHasOtherTypeOfPersonalRelationToPerson",
            new_name="VersionPersonOtherRelationToPerson",
        ),
        migrations.AlterModelOptions(
            name="versionpersonotherrelationtoperson",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical person other relation to person",
                "verbose_name_plural": "historical person other relation to persons",
            },
        ),
    ]
