# Generated by Django 5.1.3 on 2024-12-11 10:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "apis_ontology",
            "0051_rename_personhasothertypeofpersonalrelationtoperson_personotherrelationtoperson_and_more",
        ),
        ("contenttypes", "0002_remove_content_type_name"),
        ("relations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PersonRefersWithNameToTheViewsOfPerson",
            new_name="PersonQuotesWithNamePerson",
        ),
        migrations.RenameModel(
            old_name="VersionPersonRefersWithNameToTheViewsOfPerson",
            new_name="VersionPersonQuotesWithNamePerson",
        ),
        migrations.RenameModel(
            old_name="VersionPersonRefersWithNameToTheViewsOfPerson_subject_of_teaching_vocab",
            new_name="VersionPersonQuotesWithNamePerson_subject_of_teaching_vocab",
        ),
        migrations.AlterModelOptions(
            name="versionpersonquoteswithnameperson",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical person quotes with name person",
                "verbose_name_plural": "historical person quotes with name persons",
            },
        ),
        migrations.AlterModelOptions(
            name="versionpersonquoteswithnameperson_subject_of_teaching_vocab",
            options={
                "verbose_name": "VersionPersonQuotesWithNamePerson_subject_of_teaching_vocab"
            },
        ),
        migrations.RenameField(
            model_name="versionpersonquoteswithnameperson_subject_of_teaching_vocab",
            old_name="personreferswithnametotheviewsofperson",
            new_name="personquoteswithnameperson",
        ),
    ]
