# Generated by Django 5.1.3 on 2024-12-11 10:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "apis_ontology",
            "0052_rename_personreferswithnametotheviewsofperson_personquoteswithnameperson_and_more",
        ),
        ("contenttypes", "0002_remove_content_type_name"),
        ("relations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PersonRefersWithoutNameToTheViewsOfPerson",
            new_name="PersonQuotesWithoutNamePerson",
        ),
        migrations.RenameModel(
            old_name="VersionPersonRefersWithoutNameToTheViewsOfPerson",
            new_name="VersionPersonQuotesWithoutNamePerson",
        ),
        migrations.RenameModel(
            old_name="VersionPersonRefersWithoutNameToTheViewsOfPerson_subject_of_teaching_vocab",
            new_name="VersionPersonQuotesWithoutNamePerson_subject_of_teaching_vocab",
        ),
        migrations.AlterModelOptions(
            name="versionpersonquoteswithoutnameperson",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical person quotes without name person",
                "verbose_name_plural": "historical person quotes without name persons",
            },
        ),
        migrations.AlterModelOptions(
            name="versionpersonquoteswithoutnameperson_subject_of_teaching_vocab",
            options={
                "verbose_name": "VersionPersonQuotesWithoutNamePerson_subject_of_teaching_vocab"
            },
        ),
        migrations.RenameField(
            model_name="versionpersonquoteswithoutnameperson_subject_of_teaching_vocab",
            old_name="personreferswithoutnametotheviewsofperson",
            new_name="personquoteswithoutnameperson",
        ),
    ]
