# Generated by Django 5.1.3 on 2024-12-11 10:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "apis_ontology",
            "0053_rename_personreferswithoutnametotheviewsofperson_personquoteswithoutnameperson_and_more",
        ),
        ("contenttypes", "0002_remove_content_type_name"),
        ("relations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PersonRequestorOfPerson",
            new_name="PersonRequestsPerson",
        ),
        migrations.RenameModel(
            old_name="VersionPersonRequestorOfPerson",
            new_name="VersionPersonRequestsPerson",
        ),
        migrations.RenameModel(
            old_name="VersionPersonRequestorOfPerson_subject_of_teaching_vocab",
            new_name="VersionPersonRequestsPerson_subject_of_teaching_vocab",
        ),
        migrations.AlterModelOptions(
            name="versionpersonrequestsperson",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical person requests person",
                "verbose_name_plural": "historical person requests persons",
            },
        ),
        migrations.AlterModelOptions(
            name="versionpersonrequestsperson_subject_of_teaching_vocab",
            options={
                "verbose_name": "VersionPersonRequestsPerson_subject_of_teaching_vocab"
            },
        ),
        migrations.RenameField(
            model_name="versionpersonrequestsperson_subject_of_teaching_vocab",
            old_name="personrequestorofperson",
            new_name="personrequestsperson",
        ),
    ]
