# Generated by Django 5.1.3 on 2024-12-11 10:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "apis_ontology",
            "0054_rename_personrequestorofperson_personrequestsperson_and_more",
        ),
        ("contenttypes", "0002_remove_content_type_name"),
        ("relations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PersonStudiedWork",
            new_name="PersonStudiesWork",
        ),
        migrations.RenameModel(
            old_name="VersionPersonStudiedWork",
            new_name="VersionPersonStudiesWork",
        ),
        migrations.AlterModelOptions(
            name="versionpersonstudieswork",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical person studies work",
                "verbose_name_plural": "historical person studies works",
            },
        ),
    ]
