# Generated by Django 5.1.3 on 2024-12-11 10:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0055_rename_personstudiedwork_personstudieswork_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("relations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PlaceIsLocatedWithinPlace",
            new_name="PlaceLocatedWithinPlace",
        ),
        migrations.RenameModel(
            old_name="VersionPlaceIsLocatedWithinPlace",
            new_name="VersionPlaceLocatedWithinPlace",
        ),
        migrations.AlterModelOptions(
            name="versionplacelocatedwithinplace",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical place located within place",
                "verbose_name_plural": "historical place located within places",
            },
        ),
    ]
