# Generated by Django 5.1.6 on 2025-02-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "apis_ontology",
            "0056_rename_placeislocatedwithinplace_placelocatedwithinplace_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instance",
            options={
                "ordering": ["name", "pk"],
                "verbose_name": "instance",
                "verbose_name_plural": "Instances",
            },
        ),
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["name", "pk"],
                "verbose_name": "person",
                "verbose_name_plural": "Persons",
            },
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={
                "ordering": ["name"],
                "verbose_name": "Topic",
                "verbose_name_plural": "Topics",
            },
        ),
        migrations.AlterModelOptions(
            name="work",
            options={
                "ordering": ["name", "pk"],
                "verbose_name": "work",
                "verbose_name_plural": "Works",
            },
        ),
        migrations.RemoveField(
            model_name="instance",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="person",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="place",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="versioninstance",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="versionperson",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="versionplace",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="versionwork",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="work",
            name="notes",
        ),
        migrations.AlterField(
            model_name="personactiveatplace",
            name="subject_of_teaching_vocab",
            field=models.ManyToManyField(
                blank=True, to="apis_ontology.subject", verbose_name="Topic of teaching"
            ),
        ),
        migrations.AlterField(
            model_name="personlineagepredecessorofperson",
            name="subject_of_teaching_vocab",
            field=models.ManyToManyField(
                blank=True, to="apis_ontology.subject", verbose_name="Topic of teaching"
            ),
        ),
        migrations.AlterField(
            model_name="personquoteswithnameperson",
            name="subject_of_teaching_vocab",
            field=models.ManyToManyField(
                blank=True, to="apis_ontology.subject", verbose_name="Topic of teaching"
            ),
        ),
        migrations.AlterField(
            model_name="personquoteswithoutnameperson",
            name="subject_of_teaching_vocab",
            field=models.ManyToManyField(
                blank=True, to="apis_ontology.subject", verbose_name="Topic of teaching"
            ),
        ),
        migrations.AlterField(
            model_name="personrequestsperson",
            name="subject_of_teaching_vocab",
            field=models.ManyToManyField(
                blank=True, to="apis_ontology.subject", verbose_name="Topic of teaching"
            ),
        ),
        migrations.AlterField(
            model_name="personstudentofperson",
            name="subject_of_teaching_vocab",
            field=models.ManyToManyField(
                blank=True, to="apis_ontology.subject", verbose_name="Topic of teaching"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="subject_vocab",
            field=models.ManyToManyField(
                blank=True, to="apis_ontology.subject", verbose_name="Topic"
            ),
        ),
    ]
