# Generated by Django 5.1.6 on 2025-02-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0057_alter_instance_options_alter_person_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="excerpts",
            options={"verbose_name": "Excerpt", "verbose_name_plural": "Excerpts"},
        ),
        migrations.AlterModelOptions(
            name="zoteroentry",
            options={
                "verbose_name": "Zotero Entry",
                "verbose_name_plural": "Zotero Entries",
            },
        ),
    ]
