# Generated by Django 5.1.6 on 2025-02-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0058_alter_excerpts_options_alter_zoteroentry_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="excerpts",
            options={"verbose_name": "excerpt", "verbose_name_plural": "excerpts"},
        ),
        migrations.AlterModelOptions(
            name="zoteroentry",
            options={
                "verbose_name": "zotero entry",
                "verbose_name_plural": "zotero entries",
            },
        ),
        migrations.AddField(
            model_name="excerpts",
            name="tibschol_refs",
            field=models.TextField(
                blank=True, null=True, verbose_name="Tibschol reference"
            ),
        ),
    ]
