# Generated by Django 5.1.6 on 2025-02-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "apis_ontology",
            "0059_alter_excerpts_options_alter_zoteroentry_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="excerpts",
            name="status",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
