# Generated by Django 5.1.6 on 2025-02-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0060_excerpts_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="excerpts",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="excerpts",
            name="zotero_refs",
            field=models.TextField(
                blank=True, null=True, verbose_name="Zotero references"
            ),
        ),
    ]
