# Generated by Django 5.1.6 on 2025-03-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0064_remove_instance_start_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instance",
            name="start_date_written",
        ),
        migrations.RemoveField(
            model_name="person",
            name="end_date_written",
        ),
        migrations.RemoveField(
            model_name="person",
            name="start_date_written",
        ),
        migrations.RemoveField(
            model_name="place",
            name="start_date_written",
        ),
        migrations.RemoveField(
            model_name="versioninstance",
            name="start_date_written",
        ),
        migrations.RemoveField(
            model_name="versionperson",
            name="end_date_written",
        ),
        migrations.RemoveField(
            model_name="versionperson",
            name="start_date_written",
        ),
        migrations.RemoveField(
            model_name="versionplace",
            name="start_date_written",
        ),
        migrations.RemoveField(
            model_name="versionwork",
            name="start_date_written",
        ),
        migrations.RemoveField(
            model_name="work",
            name="start_date_written",
        ),
    ]
