# Generated by Django 5.1.6 on 2025-04-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0066_alter_instance_start_date_from_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="place",
            options={
                "ordering": ["label"],
                "verbose_name": "place",
                "verbose_name_plural": "Places",
            },
        ),
        migrations.RemoveField(
            model_name="versioninstance",
            name="self_contenttype",
        ),
        migrations.RemoveField(
            model_name="versionperson",
            name="self_contenttype",
        ),
        migrations.RemoveField(
            model_name="versionplace",
            name="self_contenttype",
        ),
        migrations.RemoveField(
            model_name="versionwork",
            name="self_contenttype",
        ),
        migrations.AddField(
            model_name="place",
            name="feature_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text='<a href="https://www.geonames.org/export/codes.html">Geonames Feature Code List</a>',
                max_length=16,
                verbose_name="feature code",
            ),
        ),
        migrations.AddField(
            model_name="versionplace",
            name="feature_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text='<a href="https://www.geonames.org/export/codes.html">Geonames Feature Code List</a>',
                max_length=16,
                verbose_name="feature code",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="latitude"),
        ),
        migrations.AlterField(
            model_name="place",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="longitude"),
        ),
        migrations.AlterField(
            model_name="versionplace",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="latitude"),
        ),
        migrations.AlterField(
            model_name="versionplace",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="longitude"),
        ),
    ]
