# Generated by Django 5.1.6 on 2025-04-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0067_alter_place_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="excerpts",
            name="xml_id",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="zoteroentry",
            name="zoteroId",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Zotero ID"
            ),
        ),
    ]
