# Generated by Django 5.1.8 on 2025-05-16 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0068_alter_excerpts_xml_id_alter_zoteroentry_zoteroid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instanceiscopiedfrominstance",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"],
                "verbose_name": "instance has source",
            },
        ),
        migrations.AlterModelOptions(
            name="instancewrittenatplace",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="personactiveatplace",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="personaddresseeofwork",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="personauthorofwork",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="personbiographedinwork",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="personbiographerofperson",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="personhasotherrelationwithinstance",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="personlineagepredecessorofperson",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="personordinatorofperson",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="personotherrelationtoperson",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="personownerofinstance",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="personparentofperson",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="personprompterofwork",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="personquoteswithnameperson",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="personquoteswithoutnameperson",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="personrequestsperson",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="personscribeofinstance",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="personsiblingofperson",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="personsponsorofinstance",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="personstudentofperson",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="personstudieswork",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="personteacheswork",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="persontranslatorofwork",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="personunclematernalpaternalofperson",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="placelocatedwithinplace",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="workcommentaryonwork",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="workcomposedatplace",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="workcontainscitationsofwork",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="workhasasaninstanceinstance",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="workrecordstheteachingofperson",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
        migrations.AlterModelOptions(
            name="worktaughtatplace",
            options={
                "ordering": ["subj_content_type", "obj_content_type", "confidence"]
            },
        ),
    ]
