# Generated by Django 5.1.8 on 2025-06-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0069_alter_instanceiscopiedfrominstance_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="nationality",
            field=models.CharField(
                blank=True,
                choices=[("Indic", "Indic"), ("Tibetan", "Tibetan")],
                max_length=10,
                null=True,
                verbose_name="Origin",
            ),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="nationality",
            field=models.CharField(
                blank=True,
                choices=[("Indic", "Indic"), ("Tibetan", "Tibetan")],
                max_length=10,
                null=True,
                verbose_name="Origin",
            ),
        ),
    ]
