# Generated by Django 5.2.6 on 2026-04-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0074_instance_tibetan_transliteration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="tibetan_transliteration",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Tibetan Script"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="tibetan_transliteration",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Tibetan Script"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="tibetan_transliteration",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Tibetan Script"
            ),
        ),
        migrations.AlterField(
            model_name="versioninstance",
            name="tibetan_transliteration",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Tibetan Script"
            ),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="tibetan_transliteration",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Tibetan Script"
            ),
        ),
        migrations.AlterField(
            model_name="versionplace",
            name="tibetan_transliteration",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Tibetan Script"
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="tibetan_transliteration",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Tibetan Script"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="tibetan_transliteration",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Tibetan Script"
            ),
        ),
    ]
